name: Notebook Cleaning Flow - Railway

on:
  workflow_dispatch:
  push:
    paths:
      - "CleaningAgent.py"

  workflow_run:
    workflows: ["Upload to Railway"]
    types:
      - completed

jobs:
  upload:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary openpyxl

      - name: Run Cleaning Step 1
        run: python CleaningAgent.py
        env:
          RAILWAY_DB_URL: ${{ secrets.RAILWAY_DB_URL }}
