name: Notebook Cleaning Flow

on:
  push:
    paths:
      - "CleaningAgent.py"
      - "**/*.csv"
      - "**/*.xlsx"

  workflow_run:
    workflows: ["Upload to Supabase"]
    types:
      - completed

jobs:
  run-cleaning-agent:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary openpyxl

      - name: Run Cleaning Agent
        run: python CleaningAgent.py
        env:
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
